global:
  scrape_interval: 5s
  
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.50.5:9100']
    metrics_path: /metrics
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.50.10:9090']
      
  - job_name: 'snmp'
    static_configs:
      - targets:
          - '192.168.50.51'  # R1
          - '192.168.50.52'  # R2
          - '192.168.50.53'  # R3
    metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.50.10:9116