---
- name: Deploy Node Exporter on target server
  hosts: linux_server
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
    - name: Run Node Exporter container
      docker_container:
        name: node-exporter
        image: prom/node-exporter
        ports:
          - "9100:9100"
        state: started
        restart_policy: always

- name: Deploy monitoring stack on localhost
  hosts: localhost
  connection: local
  tasks:
    - name: Run Prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus
        ports:
          - "9090:9090"
        volumes:
          - "/home/user/SRE-lab/configs/prometheus.yml:/etc/prometheus/prometheus.yml"
        state: started
        restart_policy: always

    - name: start Grafana
      docker_container:
        name: grafana
        image: grafana/grafana
        ports:
          - "3000:3000"
        state: started
        restart_policy: always