---
- name: Deploy monitoring stack
  hosts: linux_server
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
    - name: Start Node Exporter
      docker_container:
        name: node-exporter
        image: prom/node-exporter
        ports:
          - "9100:9100"
        state: started
        restart_policy: always
        
    - name: Start Prometheus
      docker_container:
        name: prometheus
        image: prom/prometheus
        ports:
          - "9090:9090"
        volumes:
          - "/home/usr/prometheus.yml:/etc/prometheus/prometheus.yml"
        state: started
        restart_policy: always

- name: Deploy Grafana
  hosts: localhost
  connection: local
  tasks:
    - name: start Grafana
      docker_container:
        name: grafana
        image: grafana/grafana
        ports:
          - "3000:3000"
        state: started
        restart_policy: always