global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.50.5:9100']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.50.5:9090']